name: Calc
markdown: redcarpet
pygments: true
permalink: none
calc_git_url: https://github.com/agordon/calc.git
calc_version: 1.0.0
calc_releases: https://github.com/agordon/calc/releases/
calc_src_tarball_filename: calc-1.0.0.tar.gz
calc_src_tarball_url: https://s3.amazonaws.com/agordon/calc/src/calc-1.0.0.tar.gz
calc_deb_64bit_url: https://s3.amazonaws.com/agordon/calc/bin/calc_1.0.0-1_amd64.deb
calc_bin_linux_64bit_url: https://s3.amazonaws.com/agordon/calc/bin/calc-1.0.0-bin__Linux__x86_64.tar.gz
calc_bin_macosx_url: https://s3.amazonaws.com/agordon/calc/bin/calc-1.0.0-bin__MacOSX_10.8.5__64bit.tar.gz
calc_bin_freebsd_64bit_url: https://s3.amazonaws.com/agordon/calc/bin/calc-1.0.0-bin__FreeBSD__10.0-RELEASE__amd64.tar.gz
